# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raiwas/Work/Qt/CookiesV3/Coookies

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raiwas/Work/Qt/CookiesV3/Coookies

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raiwas/Work/Qt/CookiesV3/Coookies/CMakeFiles /home/raiwas/Work/Qt/CookiesV3/Coookies//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raiwas/Work/Qt/CookiesV3/Coookies/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Coookies

# Build rule for target.
Coookies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Coookies
.PHONY : Coookies

# fast build rule for target.
Coookies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/build
.PHONY : Coookies/fast

#=============================================================================
# Target rules for targets named Coookies_autogen

# Build rule for target.
Coookies_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Coookies_autogen
.PHONY : Coookies_autogen

# fast build rule for target.
Coookies_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies_autogen.dir/build.make CMakeFiles/Coookies_autogen.dir/build
.PHONY : Coookies_autogen/fast

Coookies_autogen/mocs_compilation.o: Coookies_autogen/mocs_compilation.cpp.o
.PHONY : Coookies_autogen/mocs_compilation.o

# target to build an object file
Coookies_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/Coookies_autogen/mocs_compilation.cpp.o
.PHONY : Coookies_autogen/mocs_compilation.cpp.o

Coookies_autogen/mocs_compilation.i: Coookies_autogen/mocs_compilation.cpp.i
.PHONY : Coookies_autogen/mocs_compilation.i

# target to preprocess a source file
Coookies_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/Coookies_autogen/mocs_compilation.cpp.i
.PHONY : Coookies_autogen/mocs_compilation.cpp.i

Coookies_autogen/mocs_compilation.s: Coookies_autogen/mocs_compilation.cpp.s
.PHONY : Coookies_autogen/mocs_compilation.s

# target to generate assembly for a file
Coookies_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/Coookies_autogen/mocs_compilation.cpp.s
.PHONY : Coookies_autogen/mocs_compilation.cpp.s

SqWindow.o: SqWindow.cpp.o
.PHONY : SqWindow.o

# target to build an object file
SqWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SqWindow.cpp.o
.PHONY : SqWindow.cpp.o

SqWindow.i: SqWindow.cpp.i
.PHONY : SqWindow.i

# target to preprocess a source file
SqWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SqWindow.cpp.i
.PHONY : SqWindow.cpp.i

SqWindow.s: SqWindow.cpp.s
.PHONY : SqWindow.s

# target to generate assembly for a file
SqWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SqWindow.cpp.s
.PHONY : SqWindow.cpp.s

SquaredScene.o: SquaredScene.cpp.o
.PHONY : SquaredScene.o

# target to build an object file
SquaredScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SquaredScene.cpp.o
.PHONY : SquaredScene.cpp.o

SquaredScene.i: SquaredScene.cpp.i
.PHONY : SquaredScene.i

# target to preprocess a source file
SquaredScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SquaredScene.cpp.i
.PHONY : SquaredScene.cpp.i

SquaredScene.s: SquaredScene.cpp.s
.PHONY : SquaredScene.s

# target to generate assembly for a file
SquaredScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/SquaredScene.cpp.s
.PHONY : SquaredScene.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

squaredhero.o: squaredhero.cpp.o
.PHONY : squaredhero.o

# target to build an object file
squaredhero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/squaredhero.cpp.o
.PHONY : squaredhero.cpp.o

squaredhero.i: squaredhero.cpp.i
.PHONY : squaredhero.i

# target to preprocess a source file
squaredhero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/squaredhero.cpp.i
.PHONY : squaredhero.cpp.i

squaredhero.s: squaredhero.cpp.s
.PHONY : squaredhero.s

# target to generate assembly for a file
squaredhero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Coookies.dir/build.make CMakeFiles/Coookies.dir/squaredhero.cpp.s
.PHONY : squaredhero.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Coookies_autogen"
	@echo "... Coookies"
	@echo "... Coookies_autogen/mocs_compilation.o"
	@echo "... Coookies_autogen/mocs_compilation.i"
	@echo "... Coookies_autogen/mocs_compilation.s"
	@echo "... SqWindow.o"
	@echo "... SqWindow.i"
	@echo "... SqWindow.s"
	@echo "... SquaredScene.o"
	@echo "... SquaredScene.i"
	@echo "... SquaredScene.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... squaredhero.o"
	@echo "... squaredhero.i"
	@echo "... squaredhero.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

